yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path('create/', views.post_create, name='post_create'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    """Group of posters calss"""
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True,
                            verbose_name='Адрес для страницы с группой')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = "group"

    def __str__(self):
        return self.slug


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Пожалуйста напишите хоть что нибудь')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Можно и не заполнять'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = "post"

    def __str__(self):
        count_of_simbols = 15
        return self.text[:count_of_simbols]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             related_name='comments',
                             on_delete=models.CASCADE,
                             verbose_name='Пост')
    author = models.ForeignKey(User,
                               related_name='comments',
                               on_delete=models.CASCADE,
                               verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Напишите комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')


class Follow(models.Model):
    user = models.ForeignKey(User,
                             related_name='follower',
                             on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    author = models.ForeignKey(User,
                               related_name='following',
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    models.UniqueConstraint(fields=['user', 'author'],
                            name='unic_follow_record')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .forms import CommentForm, PostForm
from .models import Group, Post, Follow
from .utills import paginator_add

User = get_user_model()

POSTS_PER_PAGE = 10
HEADER_LENGTH = 30


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    post_list = Post.objects.select_related('author').all()
    page_obj = paginator_add(post_list, POSTS_PER_PAGE, request)
    context = {
        'title': title,
        'page_obj': page_obj,
        'index': True
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'

    group = get_object_or_404(Group, slug=slug)
    title = f'{group.title}'
    post_list = group.posts.all()
    page_obj = paginator_add(post_list, POSTS_PER_PAGE, request)
    context = {
        'title': title,
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = Post.objects.select_related('author').filter(author_id=author.id)
    post_count = posts.count()
    page_obj = paginator_add(posts, POSTS_PER_PAGE, request)
    title = f'{author}'
    following = Follow.objects.filter(
        user_id=request.user.id,
        author_id=author.id
    ).exists()
    context = {
        'author': author,
        'post_count': post_count,
        'page_obj': page_obj,
        'title': title,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = context_for_detail(post)
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.pub_date = datetime.now()
        post.save()

        return redirect('posts:profile', request.user)
    else:
        title = 'Добавить запись'
        is_edit = False
        context = {
            'title': title,
            'form': form,
            'is_edit': is_edit
        }
        return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == "POST" and request.user == post.author:
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:post_detail', post_id=post.pk)
    elif request.user == post.author:
        title = 'Отредактировать запись'
        context = {
            'form': form,
            'is_edit': True,
            'title': title,
        }
        return render(request, 'posts/create_post.html', context)
    else:
        context = context_for_detail(post)
        return render(request, 'posts/post_detail.html', context)


def context_for_detail(post):
    title = post.text[:HEADER_LENGTH]
    ps = Post.objects.select_related('author').filter(
        author_id=post.author_id)
    post_count = ps.count()
    comments = post.comments.all()
    form = CommentForm()
    return {
        'title': title,
        'post': post,
        'post_count': post_count,
        'comments': comments,
        'form': form
    }


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    title = 'Мои подписки'
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_add(post_list, POSTS_PER_PAGE, request)
    context = {
        'title': title,
        'page_obj': page_obj,
        'index': False,
        'follow': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(
        user_id=request.user.id,
        author_id=author.id
    ).exists()
    if not following and request.user != author:
        Follow.objects.create(
            user_id=request.user.id,
            author_id=author.id
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow_record = Follow.objects.filter(
        user_id=request.user.id,
        author_id=author.id
    )
    following = follow_record.exists()
    if following:
        follow_record.delete()
    return redirect('posts:follow_index')

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30"
                     class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
            {% comment %}
                Меню - список пунктов со стандартными классами Bootsrap.
                Класс nav-pills нужен для выделения активных пунктов
            {% endcomment %}
            {% with request.resolver_match.view_name as view_name %}
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link
                    {% if view_name  == 'about:author' %}
                     active
                    {% endif %}"
                           href="{% url 'about:author' %}"
                        >
                            Об авторе
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link
                    {% if view_name  == 'about:tech' %}
                     active
                    {% endif %}"
                           href="{% url 'about:tech' %}">Технологии</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'posts:post_create' %}">Новая
                                запись</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light
                    {% if view_name  == 'users:password_change' %}
                     active
                    {% endif %}"
                               href="{% url 'users:password_change' %}">Изменить
                                пароль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light
                    {% if view_name  == 'users:logout' %}
                     active
                    {% endif %}"
                               href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                        <li>
                           <a href="{% url 'posts:profile' user.username %}" > Пользователь: {{ user.username }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link link-light
                    {% if view_name  == 'users:login' %}
                     active
                    {% endif %}"
                               href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light
                    {% if view_name  == 'users:signup' %}
                     active
                    {% endif %}"
                               href="{% url 'users:signup' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            {% endwith %}
        </div>
    </nav>
</header>

yatube/templates/includes/posts.html
{% load thumbnail %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
    <article>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </article>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <p>{% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи
            группы</a>
    {% endif %}</p>
    {% if not forloop.last %}
        <hr>
    {% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}